export interface CurrencyDefinition {
  code: string;        // ISO 4217
  symbol: string;
  name: string;
  decimals: number;    // 0 for JPY/KRW/XOF, 3 for KWD/BHD/OMR, standard 2 for most others
}

export const SUPPORTED_CURRENCIES: Record<string, CurrencyDefinition> = {
  AED: { code: "AED", symbol: "AED", name: "United Arab Emirates Dirham", decimals: 2 },
  AFN: { code: "AFN", symbol: "؋", name: "Afghan Afghani", decimals: 2 },
  ALL: { code: "ALL", symbol: "L", name: "Albanian Lek", decimals: 2 },
  AMD: { code: "AMD", symbol: "֏", name: "Armenian Dram", decimals: 2 },
  ANG: { code: "ANG", symbol: "NAƒ", name: "Netherlands Antillean Guilder", decimals: 2 },
  AOA: { code: "AOA", symbol: "Kz", name: "Angolan Kwanza", decimals: 2 },
  ARS: { code: "ARS", symbol: "$", name: "Argentine Peso", decimals: 2 },
  AUD: { code: "AUD", symbol: "A$", name: "Australian Dollar", decimals: 2 },
  AWG: { code: "AWG", symbol: "Afl.", name: "Aruban Florin", decimals: 2 },
  AZN: { code: "AZN", symbol: "₼", name: "Azerbaijani Manat", decimals: 2 },
  BAM: { code: "BAM", symbol: "KM", name: "Bosnia-Herzegovina Convertible Mark", decimals: 2 },
  BBD: { code: "BBD", symbol: "Bds$", name: "Barbadian Dollar", decimals: 2 },
  BDT: { code: "BDT", symbol: "৳", name: "Bangladeshi Taka", decimals: 2 },
  BGN: { code: "BGN", symbol: "lv", name: "Bulgarian Lev", decimals: 2 },
  BHD: { code: "BHD", symbol: "BD", name: "Bahraini Dinar", decimals: 3 },
  BIF: { code: "BIF", symbol: "FBu", name: "Burundian Franc", decimals: 0 },
  BMD: { code: "BMD", symbol: "BD$", name: "Bermudian Dollar", decimals: 2 },
  BND: { code: "BND", symbol: "B$", name: "Brunei Dollar", decimals: 2 },
  BOB: { code: "BOB", symbol: "Bs.", name: "Bolivian Boliviano", decimals: 2 },
  BRL: { code: "BRL", symbol: "R$", name: "Brazilian Real", decimals: 2 },
  BSD: { code: "BSD", symbol: "B$", name: "Bahamian Dollar", decimals: 2 },
  BTN: { code: "BTN", symbol: "Nu.", name: "Bhutanese Ngultrum", decimals: 2 },
  BWP: { code: "BWP", symbol: "P", name: "Botswanan Pula", decimals: 2 },
  BYN: { code: "BYN", symbol: "Br", name: "Belarusian Ruble", decimals: 2 },
  BZD: { code: "BZD", symbol: "BZ$", name: "Belize Dollar", decimals: 2 },
  CAD: { code: "CAD", symbol: "CA$", name: "Canadian Dollar", decimals: 2 },
  CDF: { code: "CDF", symbol: "FC", name: "Congolese Franc", decimals: 2 },
  CHF: { code: "CHF", symbol: "CHF", name: "Swiss Franc", decimals: 2 },
  CLP: { code: "CLP", symbol: "$", name: "Chilean Peso", decimals: 0 },
  CNY: { code: "CNY", symbol: "¥", name: "Chinese Yuan", decimals: 2 },
  COP: { code: "COP", symbol: "$", name: "Colombian Peso", decimals: 2 },
  CRC: { code: "CRC", symbol: "₡", name: "Costa Rican Colón", decimals: 2 },
  CUP: { code: "CUP", symbol: "$", name: "Cuban Peso", decimals: 2 },
  CVE: { code: "CVE", symbol: "Esc", name: "Cape Verdean Escudo", decimals: 2 },
  CZK: { code: "CZK", symbol: "Kč", name: "Czech Koruna", decimals: 2 },
  DJF: { code: "DJF", symbol: "Fdj", name: "Djiboutian Franc", decimals: 0 },
  DKK: { code: "DKK", symbol: "kr.", name: "Danish Krone", decimals: 2 },
  DOP: { code: "DOP", symbol: "RD$", name: "Dominican Peso", decimals: 2 },
  DZD: { code: "DZD", symbol: "DA", name: "Algerian Dinar", decimals: 2 },
  EGP: { code: "EGP", symbol: "E£", name: "Egyptian Pound", decimals: 2 },
  ERN: { code: "ERN", symbol: "Nfk", name: "Eritrean Nakfa", decimals: 2 },
  ETB: { code: "ETB", symbol: "Br", name: "Ethiopian Birr", decimals: 2 },
  EUR: { code: "EUR", symbol: "€", name: "Euro", decimals: 2 },
  FJD: { code: "FJD", symbol: "FJ$", name: "Fijian Dollar", decimals: 2 },
  FKP: { code: "FKP", symbol: "£", name: "Falkland Islands Pound", decimals: 2 },
  GBP: { code: "GBP", symbol: "£", name: "British Pound", decimals: 2 },
  GEL: { code: "GEL", symbol: "₾", name: "Georgian Lari", decimals: 2 },
  GHS: { code: "GHS", symbol: "GH₵", name: "Ghanaian Cedi", decimals: 2 },
  GIP: { code: "GIP", symbol: "£", name: "Gibraltar Pound", decimals: 2 },
  GMD: { code: "GMD", symbol: "D", name: "Gambian Dalasi", decimals: 2 },
  GNF: { code: "GNF", symbol: "FG", name: "Guinean Franc", decimals: 0 },
  GTQ: { code: "GTQ", symbol: "Q", name: "Guatemalan Quetzal", decimals: 2 },
  GYD: { code: "GYD", symbol: "G$", name: "Guyanaese Dollar", decimals: 2 },
  HKD: { code: "HKD", symbol: "HK$", name: "Hong Kong Dollar", decimals: 2 },
  HNL: { code: "HNL", symbol: "L", name: "Honduran Lempira", decimals: 2 },
  HTG: { code: "HTG", symbol: "G", name: "Haitian Gourde", decimals: 2 },
  HUF: { code: "HUF", symbol: "Ft", name: "Hungarian Forint", decimals: 2 },
  IDR: { code: "IDR", symbol: "Rp", name: "Indonesian Rupiah", decimals: 2 },
  ILS: { code: "ILS", symbol: "₪", name: "Israeli New Shekel", decimals: 2 },
  INR: { code: "INR", symbol: "₹", name: "Indian Rupee", decimals: 2 },
  IQD: { code: "IQD", symbol: "IQD", name: "Iraqi Dinar", decimals: 3 },
  IRR: { code: "IRR", symbol: "﷼", name: "Iranian Rial", decimals: 2 },
  ISK: { code: "ISK", symbol: "kr", name: "Icelandic Króna", decimals: 0 },
  JMD: { code: "JMD", symbol: "J$", name: "Jamaican Dollar", decimals: 2 },
  JOD: { code: "JOD", symbol: "JD", name: "Jordanian Dinar", decimals: 3 },
  JPY: { code: "JPY", symbol: "¥", name: "Japanese Yen", decimals: 0 },
  KES: { code: "KES", symbol: "KSh", name: "Kenyan Shilling", decimals: 2 },
  KGS: { code: "KGS", symbol: "som", name: "Kyrgyzstani Som", decimals: 2 },
  KHR: { code: "KHR", symbol: "៛", name: "Cambodian Riel", decimals: 2 },
  KMF: { code: "KMF", symbol: "CF", name: "Comorian Franc", decimals: 0 },
  KPW: { code: "KPW", symbol: "₩", name: "North Korean Won", decimals: 2 },
  KRW: { code: "KRW", symbol: "₩", name: "South Korean Won", decimals: 0 },
  KWD: { code: "KWD", symbol: "KD", name: "Kuwaiti Dinar", decimals: 3 },
  KYD: { code: "KYD", symbol: "CI$", name: "Cayman Islands Dollar", decimals: 2 },
  KZT: { code: "KZT", symbol: "₸", name: "Kazakhstani Tenge", decimals: 2 },
  LAK: { code: "LAK", symbol: "₭", name: "Laotian Kip", decimals: 2 },
  LBP: { code: "LBP", symbol: "L£", name: "Lebanese Pound", decimals: 2 },
  LKR: { code: "LKR", symbol: "Rs", name: "Sri Lankan Rupee", decimals: 2 },
  LRD: { code: "LRD", symbol: "L$", name: "Liberian Dollar", decimals: 2 },
  LSL: { code: "LSL", symbol: "L", name: "Lesotho Loti", decimals: 2 },
  LYD: { code: "LYD", symbol: "LD", name: "Libyan Dinar", decimals: 3 },
  MAD: { code: "MAD", symbol: "MAD", name: "Moroccan Dirham", decimals: 2 },
  MDL: { code: "MDL", symbol: "L", name: "Moldovan Leu", decimals: 2 },
  MGA: { code: "MGA", symbol: "Ar", name: "Malagasy Ariary", decimals: 2 },
  MKD: { code: "MKD", symbol: "den", name: "Macedonian Denar", decimals: 2 },
  MMK: { code: "MMK", symbol: "K", name: "Myanmar Kyat", decimals: 2 },
  MNT: { code: "MNT", symbol: "₮", name: "Mongolian Tugrik", decimals: 2 },
  MOP: { code: "MOP", symbol: "MOP$", name: "Macanese Pataca", decimals: 2 },
  MRU: { code: "MRU", symbol: "UM", name: "Mauritanian Ouguiya", decimals: 2 },
  MUR: { code: "MUR", symbol: "₨", name: "Mauritian Rupee", decimals: 2 },
  MVR: { code: "MVR", symbol: "Rf", name: "Maldivian Rufiyaa", decimals: 2 },
  MWK: { code: "MWK", symbol: "MK", name: "Malawian Kwacha", decimals: 2 },
  MXN: { code: "MXN", symbol: "Mex$", name: "Mexican Peso", decimals: 2 },
  MYR: { code: "MYR", symbol: "RM", name: "Malaysian Ringgit", decimals: 2 },
  MZN: { code: "MZN", symbol: "MT", name: "Mozambican Metical", decimals: 2 },
  NAD: { code: "NAD", symbol: "N$", name: "Namibian Dollar", decimals: 2 },
  NGN: { code: "NGN", symbol: "₦", name: "Nigerian Naira", decimals: 2 },
  NIO: { code: "NIO", symbol: "C$", name: "Nicaraguan Córdoba", decimals: 2 },
  NOK: { code: "NOK", symbol: "kr", name: "Norwegian Krone", decimals: 2 },
  NPR: { code: "NPR", symbol: "Rs", name: "Nepalese Rupee", decimals: 2 },
  NZD: { code: "NZD", symbol: "NZ$", name: "New Zealand Dollar", decimals: 2 },
  OMR: { code: "OMR", symbol: "OMR", name: "Omani Rial", decimals: 3 },
  PAB: { code: "PAB", symbol: "B/.", name: "Panamanian Balboa", decimals: 2 },
  PEN: { code: "PEN", symbol: "S/", name: "Peruvian Sol", decimals: 2 },
  PGK: { code: "PGK", symbol: "K", name: "Papua New Guinean Kina", decimals: 2 },
  PHP: { code: "PHP", symbol: "₱", name: "Philippine Peso", decimals: 2 },
  PKR: { code: "PKR", symbol: "Rs", name: "Pakistani Rupee", decimals: 2 },
  PLN: { code: "PLN", symbol: "zł", name: "Polish Zloty", decimals: 2 },
  PYG: { code: "PYG", symbol: "₲", name: "Paraguayan Guarani", decimals: 0 },
  QAR: { code: "QAR", symbol: "QR", name: "Qatari Riyal", decimals: 2 },
  RON: { code: "RON", symbol: "lei", name: "Romanian Leu", decimals: 2 },
  RSD: { code: "RSD", symbol: "din.", name: "Serbian Dinar", decimals: 2 },
  RUB: { code: "RUB", symbol: "₽", name: "Russian Ruble", decimals: 2 },
  RWF: { code: "RWF", symbol: "FRw", name: "Rwandan Franc", decimals: 0 },
  SAR: { code: "SAR", symbol: "SR", name: "Saudi Riyal", decimals: 2 },
  SBD: { code: "SBD", symbol: "SI$", name: "Solomon Islands Dollar", decimals: 2 },
  SCR: { code: "SCR", symbol: "SR", name: "Seychellois Rupee", decimals: 2 },
  SDG: { code: "SDG", symbol: "SDG", name: "Sudanese Pound", decimals: 2 },
  SEK: { code: "SEK", symbol: "kr", name: "Swedish Krona", decimals: 2 },
  SGD: { code: "SGD", symbol: "S$", name: "Singapore Dollar", decimals: 2 },
  SHP: { code: "SHP", symbol: "£", name: "Saint Helena Pound", decimals: 2 },
  SLE: { code: "SLE", symbol: "Le", name: "Sierra Leonean Leone", decimals: 2 },
  SOS: { code: "SOS", symbol: "Sh", name: "Somali Shilling", decimals: 2 },
  SRD: { code: "SRD", symbol: "Sr$", name: "Surinamese Dollar", decimals: 2 },
  SSP: { code: "SSP", symbol: "£", name: "South Sudanese Pound", decimals: 2 },
  STN: { code: "STN", symbol: "Db", name: "São Tomé & Príncipe Dobra", decimals: 2 },
  SYP: { code: "SYP", symbol: "LS", name: "Syrian Pound", decimals: 2 },
  SZL: { code: "SZL", symbol: "E", name: "Eswatini Lilangeni", decimals: 2 },
  THB: { code: "THB", symbol: "฿", name: "Thai Baht", decimals: 2 },
  TJS: { code: "TJS", symbol: "SM", name: "Tajikistani Somoni", decimals: 2 },
  TMT: { code: "TMT", symbol: "m", name: "Turkmenistani Manat", decimals: 2 },
  TND: { code: "TND", symbol: "DT", name: "Tunisian Dinar", decimals: 3 },
  TOP: { code: "TOP", symbol: "T$", name: "Tongan Paʻanga", decimals: 2 },
  TRY: { code: "TRY", symbol: "₺", name: "Turkish Lira", decimals: 2 },
  TTD: { code: "TTD", symbol: "TT$", name: "Trinidad & Tobago Dollar", decimals: 2 },
  TWD: { code: "TWD", symbol: "NT$", name: "New Taiwan Dollar", decimals: 2 },
  TZS: { code: "TZS", symbol: "TSh", name: "Tanzanian Shilling", decimals: 2 },
  UAH: { code: "UAH", symbol: "₴", name: "Ukrainian Hryvnia", decimals: 2 },
  UGX: { code: "UGX", symbol: "USh", name: "Ugandan Shilling", decimals: 0 },
  USD: { code: "USD", symbol: "$", name: "US Dollar", decimals: 2 },
  UYU: { code: "UYU", symbol: "$U", name: "Uruguayan Peso", decimals: 2 },
  UZS: { code: "UZS", symbol: "soʻm", name: "Uzbekistani Som", decimals: 2 },
  VES: { code: "VES", symbol: "Bs.S", name: "Venezuelan Bolívar Soberano", decimals: 2 },
  VND: { code: "VND", symbol: "₫", name: "Vietnamese Dong", decimals: 0 },
  VUV: { code: "VUV", symbol: "VT", name: "Vanuatu Vatu", decimals: 0 },
  WST: { code: "WST", symbol: "WS$", name: "Samoan Tala", decimals: 2 },
  XAF: { code: "XAF", symbol: "FCFA", name: "Central African CFA Franc", decimals: 0 },
  XCD: { code: "XCD", symbol: "EC$", name: "East Caribbean Dollar", decimals: 2 },
  XOF: { code: "XOF", symbol: "CFA", name: "West African CFA Franc", decimals: 0 },
  XPF: { code: "XPF", symbol: "CFP", name: "CFP Franc", decimals: 0 },
  YER: { code: "YER", symbol: "YR", name: "Yemeni Rial", decimals: 2 },
  ZAR: { code: "ZAR", symbol: "R", name: "South African Rand", decimals: 2 },
  ZMW: { code: "ZMW", symbol: "ZK", name: "Zambian Kwacha", decimals: 2 },
  ZWG: { code: "ZWG", symbol: "ZiG", name: "Zimbabwe Gold", decimals: 2 },
};

export function isSupportedCurrency(code: string): boolean {
  return code in SUPPORTED_CURRENCIES;
}

export function getCurrencyDefinition(code: string): CurrencyDefinition {
  return SUPPORTED_CURRENCIES[code?.toUpperCase()] ?? SUPPORTED_CURRENCIES.NGN;
}

export function formatCurrency(amount: number, currencyCode: string, locale = "en-US"): string {
  const def = getCurrencyDefinition(currencyCode);
  return new Intl.NumberFormat(locale, {
    style: "currency",
    currency: def.code,
    minimumFractionDigits: def.decimals,
    maximumFractionDigits: def.decimals,
  }).format(amount);
}

// Maps ISO 3166-1 alpha-2 country codes to official ISO 4217 currency codes.
// Exported (not just the lookup function) so UI code — e.g. an onboarding
// country/currency selector — can enumerate the full list of supported
// countries without duplicating it.
export const COUNTRY_CURRENCY_MAP: Record<string, string> = {
  AD: "EUR", AE: "AED", AF: "AFN", AG: "XCD", AI: "XCD", AL: "ALL", AM: "AMD", AO: "AOA",
  AQ: "USD", AR: "ARS", AS: "USD", AT: "EUR", AU: "AUD", AW: "AWG", AX: "EUR", AZ: "AZN",
  BA: "BAM", BB: "BBD", BD: "BDT", BE: "EUR", BF: "XOF", BG: "BGN", BH: "BHD", BI: "BIF",
  BJ: "XOF", BL: "EUR", BM: "BMD", BN: "BND", BO: "BOB", BQ: "USD", BR: "BRL", BS: "BSD",
  BT: "BTN", BV: "NOK", BW: "BWP", BY: "BYN", BZ: "BZD", CA: "CAD", CC: "AUD", CD: "CDF",
  CF: "XAF", CG: "XAF", CH: "CHF", CI: "XOF", CK: "NZD", CL: "CLP", CM: "XAF", CN: "CNY",
  CO: "COP", CR: "CRC", CU: "CUP", CV: "CVE", CW: "ANG", CX: "AUD", CY: "EUR", CZ: "CZK",
  DE: "EUR", DJ: "DJF", DK: "DKK", DM: "XCD", DO: "DOP", DZ: "DZD", EC: "USD", EE: "EUR",
  EG: "EGP", EH: "MAD", ER: "ERN", ES: "EUR", ET: "ETB", FI: "EUR", FJ: "FJD", FK: "FKP",
  FM: "USD", FO: "DKK", FR: "EUR", GA: "XAF", GB: "GBP", GD: "XCD", GE: "GEL", GF: "EUR",
  GG: "GBP", GH: "GHS", GI: "GIP", GL: "DKK", GM: "GMD", GN: "GNF", GP: "EUR", GQ: "XAF",
  GR: "EUR", GS: "GBP", GT: "GTQ", GU: "USD", GW: "XOF", GY: "GYD", HK: "HKD", HM: "AUD",
  HN: "HNL", HR: "EUR", HT: "HTG", HU: "HUF", ID: "IDR", IE: "EUR", IL: "ILS", IM: "GBP",
  IN: "INR", IO: "USD", IQ: "IQD", IR: "IRR", IS: "ISK", IT: "EUR", JE: "GBP", JM: "JMD",
  JO: "JOD", JP: "JPY", KE: "KES", KG: "KGS", KH: "KHR", KI: "AUD", KM: "KMF", KN: "XCD",
  KP: "KPW", KR: "KRW", KW: "KWD", KY: "KYD", KZ: "KZT", LA: "LAK", LB: "LBP", LC: "XCD",
  LI: "CHF", LK: "LKR", LR: "LRD", LS: "LSL", LT: "EUR", LU: "EUR", LV: "EUR", LY: "LYD",
  MA: "MAD", MC: "EUR", MD: "MDL", ME: "EUR", MF: "EUR", MG: "MGA", MH: "USD", MK: "MKD",
  ML: "XOF", MM: "MMK", MN: "MNT", MO: "MOP", MP: "USD", MQ: "EUR", MR: "MRU", MS: "XCD",
  MT: "EUR", MU: "MUR", MV: "MVR", MW: "MWK", MX: "MXN", MY: "MYR", MZ: "MZN", NA: "NAD",
  NC: "XPF", NE: "XOF", NF: "AUD", NG: "NGN", NI: "NIO", NL: "EUR", NO: "NOK", NP: "NPR",
  NR: "AUD", NU: "NZD", NZ: "NZD", OM: "OMR", PA: "PAB", PE: "PEN", PF: "XPF", PG: "PGK",
  PH: "PHP", PK: "PKR", PL: "PLN", PM: "EUR", PN: "NZD", PR: "USD", PS: "ILS", PT: "EUR",
  PW: "USD", PY: "PYG", QA: "QAR", RE: "EUR", RO: "RON", RS: "RSD", RU: "RUB", RW: "RWF",
  SA: "SAR", SB: "SBD", SC: "SCR", SD: "SDG", SE: "SEK", SG: "SGD", SH: "SHP", SI: "EUR",
  SJ: "NOK", SK: "EUR", SL: "SLE", SM: "EUR", SN: "XOF", SO: "SOS", SR: "SRD", SS: "SSP",
  ST: "STN", SV: "USD", SX: "ANG", SY: "SYP", SZ: "SZL", TC: "USD", TD: "XAF", TF: "EUR",
  TG: "XOF", TH: "THB", TJ: "TJS", TK: "NZD", TL: "USD", TM: "TMT", TN: "TND", TO: "TOP",
  TR: "TRY", TT: "TTD", TV: "AUD", TW: "TWD", TZ: "TZS", UA: "UAH", UG: "UGX", UM: "USD",
  US: "USD", UY: "UYU", UZ: "UZS", VA: "EUR", VC: "XCD", VE: "VES", VG: "USD", VI: "USD",
  VN: "VND", VU: "VUV", WF: "XPF", WS: "WST", XK: "EUR", YE: "YER", YT: "EUR", ZA: "ZAR",
  ZM: "ZMW", ZW: "ZWG",
};

export const SUPPORTED_COUNTRIES = Object.keys(COUNTRY_CURRENCY_MAP);

export function defaultCurrencyForCountry(countryCode: string): string {
  const formattedCode = countryCode?.toUpperCase() ?? "";
  return COUNTRY_CURRENCY_MAP[formattedCode] ?? "NGN";
}

export function formatAmount(amount: number, code: string, currencies: CurrencyDefinition[]): string {
  const def = currencies.find((c) => c.code === code) ?? { symbol: code, decimals: 2 };
  const number = new Intl.NumberFormat("en-US", {
    style: "decimal", // ← formatting only, no currency/symbol resolution involved
    minimumFractionDigits: def.decimals,
    maximumFractionDigits: def.decimals,
  }).format(amount);
  return `${def.symbol}${number}`;
}